name: NuGet Generation

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v3
        with:
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}        
          
      - name: Create NuGet package
        run: |
          cd DraftKings.LineupGenerator.Console
          dotnet pack -c Release -o out

      - name: Push NuGet package
        run: dotnet nuget push ./DraftKings.LineupGenerator.Console/out/*.nupkg --api-key ${{secrets.NUGET_TOKEN}} --skip-duplicate --no-symbols true
        continue-on-error: true