name: NuGet Generation

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Deploy NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/jwoodman510/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}        
          
      - name: Create NuGet package
        run: |
          cd DraftKings.LineupGenerator.Console
          dotnet pack -c Release -o out

      - name: Push NuGet package
        run: dotnet nuget push ./DraftKings.LineupGenerator.Console/out/*.nupkg --skip-duplicate --no-symbols true